//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISProject.Models.SISDB_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.Lecturers_Courses = new HashSet<Lecturers_Courses>();
            this.Students_Courses = new HashSet<Students_Courses>();
        }
    
        public int TableID { get; set; }
        public string c_Name { get; set; }
        public Nullable<int> c_ECTS { get; set; }
        public string c_Term { get; set; }
        public int c_Departments_TableID { get; set; }
    
        public virtual Deparments Deparments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecturers_Courses> Lecturers_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students_Courses> Students_Courses { get; set; }
    }
}
