//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISProject.Models.SISDB_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Courses
    {
        public int TableID { get; set; }
        public int sc_Users_TableID { get; set; }
        public int sc_Courses_TableID { get; set; }
        public Nullable<int> sc_Midterm_Grade { get; set; }
        public Nullable<int> sc_Final_Grade { get; set; }
        public Nullable<int> sc_Resit_Grade { get; set; }
        public Nullable<double> sc_Grade { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Users Users { get; set; }
    }
}
