//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISProject.Models.SISDB_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Lecturers_Courses = new HashSet<Lecturers_Courses>();
            this.Students_Courses = new HashSet<Students_Courses>();
        }
    
        public int TableID { get; set; }
        public string u_Citizen_Number { get; set; }
        public string u_Login_Number { get; set; }
        public string u_Name { get; set; }
        public string u_Password { get; set; }
        public string u_eMail { get; set; }
        public string u_Phone_Number { get; set; }
        public string u_Address { get; set; }
        public string u_Title { get; set; }
        public Nullable<System.DateTime> u_Registration_Date { get; set; }
        public int u_Groups_TableID { get; set; }
        public int u_Departments_TableID { get; set; }
        public string u_Picture { get; set; }
    
        public virtual Deparments Deparments { get; set; }
        public virtual Groups Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecturers_Courses> Lecturers_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students_Courses> Students_Courses { get; set; }
    }
}
